controllers/EquipoController.php
<?php

namespace app\controllers;

use app\models\Equipo;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EquipoController implements the CRUD actions for Equipo model.
 */
class EquipoController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Equipo models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Equipo::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'nomequipo' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Equipo model.
     * @param string $nomequipo Nomequipo
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($nomequipo)
    {
        return $this->render('view', [
            'model' => $this->findModel($nomequipo),
        ]);
    }

    /**
     * Creates a new Equipo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Equipo();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'nomequipo' => $model->nomequipo]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Equipo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $nomequipo Nomequipo
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($nomequipo)
    {
        $model = $this->findModel($nomequipo);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'nomequipo' => $model->nomequipo]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Equipo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $nomequipo Nomequipo
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($nomequipo)
    {
        $this->findModel($nomequipo)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Equipo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $nomequipo Nomequipo
     * @return Equipo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($nomequipo)
    {
        if (($model = Equipo::findOne(['nomequipo' => $nomequipo])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/EtapaController.php
<?php

namespace app\controllers;

use app\models\Etapa;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EtapaController implements the CRUD actions for Etapa model.
 */
class EtapaController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Etapa models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Etapa::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'numetapa' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Etapa model.
     * @param int $numetapa Numetapa
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($numetapa)
    {
        return $this->render('view', [
            'model' => $this->findModel($numetapa),
        ]);
    }

    /**
     * Creates a new Etapa model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Etapa();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'numetapa' => $model->numetapa]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Etapa model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $numetapa Numetapa
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($numetapa)
    {
        $model = $this->findModel($numetapa);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'numetapa' => $model->numetapa]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Etapa model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $numetapa Numetapa
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($numetapa)
    {
        $this->findModel($numetapa)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Etapa model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $numetapa Numetapa
     * @return Etapa the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($numetapa)
    {
        if (($model = Etapa::findOne(['numetapa' => $numetapa])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/LlevaController.php
<?php

namespace app\controllers;

use app\models\lleva;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LlevaController implements the CRUD actions for lleva model.
 */
class LlevaController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all lleva models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => lleva::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'numetapa' => SORT_DESC,
                    'código' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single lleva model.
     * @param int $numetapa Numetapa
     * @param string $código Código
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($numetapa, $código)
    {
        return $this->render('view', [
            'model' => $this->findModel($numetapa, $código),
        ]);
    }

    /**
     * Creates a new lleva model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new lleva();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'numetapa' => $model->numetapa, 'código' => $model->código]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing lleva model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $numetapa Numetapa
     * @param string $código Código
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($numetapa, $código)
    {
        $model = $this->findModel($numetapa, $código);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'numetapa' => $model->numetapa, 'código' => $model->código]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing lleva model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $numetapa Numetapa
     * @param string $código Código
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($numetapa, $código)
    {
        $this->findModel($numetapa, $código)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the lleva model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $numetapa Numetapa
     * @param string $código Código
     * @return lleva the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($numetapa, $código)
    {
        if (($model = lleva::findOne(['numetapa' => $numetapa, 'código' => $código])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->actionTopciclistas();
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }
    
    public function actionNoticias() {
        return $this->render('noticias');
    }
    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
        
    public function actionDatos(){
        return $this->render('datos');
    }   
    
    public function actionNoticia($num){        
        return $this->render('noticia'.$num);
    }
    
    /*
     * esta funcion se ejecuta desde la funcion actionIndex, lo que hace es realizar una consulta y devuelve un render 
     * y tres variables donde se guardan los datos de las consultas para poder usarlos en la vista
     */
    
    public function actionTopciclistas(){
        //consulta que calcula el top 3 de equipos
        $topEquipos = Yii::$app->db->createCommand("select nomequipo from(SELECT e.dorsal, COUNT(*) AS victorias, c.nomequipo FROM etapa e LEFT JOIN ciclista c ON e.dorsal = c.dorsal GROUP BY c.nomequipo ORDER BY victorias DESC LIMIT 3) AS a")->queryAll();
        // consulta que calcula el top 3 de escaladores
        $topEscaladores = Yii::$app->db->createCommand("SELECT nombre FROM (SELECT p.dorsal, c.nombre, COUNT(*) AS victorias FROM  puerto p LEFT JOIN ciclista c ON p.dorsal = c.dorsal GROUP BY p.dorsal ORDER BY victorias DESC LIMIT 3) AS a")->queryAll();
        // consulta que calcula el top 3 de ciclistas
        $dorsalGanador = Yii::$app->db->createCommand("SELECT nombre FROM(SELECT e.dorsal, COUNT(*) AS victorias, c.nombre FROM etapa e LEFT JOIN ciclista c ON e.dorsal = c.dorsal GROUP BY dorsal ORDER BY victorias DESC limit 3) AS a")->queryAll();
        
        return $this->render("index",[
            "dorsal"=>$dorsalGanador,
            "topequipos"=>$topEquipos,
            "topescaladores"=>$topEscaladores,
        ]);
    }
    
}

// ------CONSULTAS-------

/*
 * consulta top 3 ciclista de la vuelta
 * 
 * SELECT nombre FROM(SELECT e.dorsal, COUNT(*) AS victorias, c.nombre FROM etapa e LEFT JOIN ciclista c ON e.dorsal = c.dorsal GROUP BY dorsal ORDER BY victorias DESC limit 3) AS a
 */

/*
 * consulta top 3 mejores equipos
 * 
 * select nomequipo from(SELECT e.dorsal, COUNT(*) AS victorias, c.nomequipo FROM etapa e LEFT JOIN ciclista c ON e.dorsal = c.dorsal GROUP BY c.nomequipo ORDER BY victorias DESC LIMIT 3) AS a
 */

/*
 * consulta usada para sacar los tres mejores escaladores de la vielta
 * SELECT nombre FROM (SELECT p.dorsal, c.nombre, COUNT(*) AS victorias FROM  puerto p LEFT JOIN ciclista c ON p.dorsal = c.dorsal GROUP BY p.dorsal ORDER BY victorias DESC LIMIT 3) AS a
 */

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/datos.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'Datos generales';

?>
<div class="container">
    
    <div class="body-content">
        <div class="jumbotron text-center bg-transparent">
            <h1 class="display-4" style="padding-top: 15px">Información</h1>
        </div>
        <div class="row">
            
            <div class="col-sm-6 col-md-4 "> 
                <div class="card alturaminima shadow-sm">
                    
                    <div class="card-body tarjeta">
                        
                        <h3>Ciclistas</h3>
                        <p>Todos los ciclistas inscritos</p>
                           
                            <?= Html::a(Html::img('@web/images/ciclista.jpg',['width'=>'278','height'=>'150']),['/ciclista/index'],['class'=> 'imageneshome'])?>
                       
                    </div>
                </div>
             </div>  
            
             <div class="col-sm-6 col-md-4"> 
                <div class="card alturaminima shadow-sm">
                    <div class="card-body tarjeta">
                        <h3>Equipos</h3>    
                        <p>Equipos han participado</p>
                        
                            <?= Html::a(Html::img('@web/images/equipo.jpg',['width'=>'278','height'=>'150']),['/equipo/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
             </div>  
            
            <div class="col-sm-6 col-md-4"> 
                <div class="card alturaminima shadow-sm">
                    <div class="card-body tarjeta">
                        <h3>Etapas</h3>
                        <p>Todas las etapas que hay</p>
                        
                        <?= Html::a(Html::img('@web/images/etapa.jpg',['width'=>'278','height'=>'150']),['/etapa/index'],['class'=> 'imageneshome']) ?>
                        
                    </div>
                </div>
             </div>   
        
         
            <div class="col-sm-6 col-md-4"> 
                <div class="card alturaminima shadow-sm">
                    
                    <div class="card-body tarjeta">
                        
                        <h3>Maillots</h3>
                        <p>Todas las Maillots que hay</p>
                        
                         <?= Html::a(Html::img('@web/images/maillots.jfif',['width'=>'278','height'=>'150']),['/maillot/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
             </div>  
            
             <div class="col-sm-6 col-md-4"> 
                <div class="card alturaminima shadow-sm">
                    <div class="card-body tarjeta">
                        <h3>Puertos</h3>    
                        <p>Puertos que hay</p>
                        
                         <?= Html::a(Html::img('@web/images/puerto.jpg',['width'=>'278','height'=>'150']),['/puerto/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
             </div>  
            
            <div class="col-sm-6 col-md-4"> 
                <div class="card alturaminima shadow-sm">
                    <div class="card-body tarjeta">
                        <h3>LLevados</h3>
                        <p>Dorsal que ha llevado el ciclista</p>
                        
                         <?= Html::a(Html::img('@web/images/dorsalllevado.jpg',['width'=>'278','height'=>'150']),['/lleva/index'],['class'=> 'imageneshome'])?>
                        
                    </div>
                </div>
             </div> 
            </div>
    </div>
    </div> 

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
//use yii\widgets\ListView;
use yii\helpers\Html;
$this->title = 'La vuelta';
?>
<div class="container-fluid">
    <div class="row stilobody">
        <div class=" col-sm-12 col-md-8 col-lg-10 ">
            <div class="size-carousel-flex shadow-sm" style="background-color: #545454">
                <!--Carousel Wrapper-->
                <div id="carousel-example-2" class="carousel slide carousel-fade" data-ride="carousel">
                  <!--Indicators-->
                  <ol class="carousel-indicators">
                    <li data-target="#carousel-example-2" data-slide-to="0" class="active"> </li>
                    <li data-target="#carousel-example-2" data-slide-to="1"></li>
                    <li data-target="#carousel-example-2" data-slide-to="2"></li>
                  </ol>
                  <!--/.Indicators-->
                  <!--Slides-->
                  <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                      <div class="view">
                        <?= Html::img("@web/images/1.png",['class'=>"d-block fotocarusel"])?>
                        <div class="mask rgba-black-light"></div>
                      </div>
                        <div class="carousel-caption" style="padding-bottom: 420px">
                            <h3 class="h3-responsive">Top 3 ciclistas de la vuelta </h3>
                        </div>
                        <div class="carousel-caption" style="padding-bottom: 10px">
                        <p>1º. <?= implode($dorsal[0])?></p>
                        <p>2º. <?= implode($dorsal[1])?> </p>
                        <p>3º. <?= implode($dorsal[2])?></p>
                      </div>
                    </div>
                    <div class="carousel-item size-carousel">
                      <!--Mask color-->
                      <div class="view">
                        <?= Html::img("@web/images/2.png",['class'=>"d-block fotocarusel"])?>
                        <div class="mask rgba-black-strong"></div>
                      </div>
                        <div class="carousel-caption" style="padding-bottom: 420px">
                            <h3 class="h3-responsive">Top 3 mejores equipos </h3>
                        </div>
                        <div class="carousel-caption" style="padding-bottom: 10px">
                        <p>1º. <?= implode($topequipos[0])?></p>
                        <p>2º. <?= implode($topequipos[1])?> </p>
                        <p>3º. <?= implode($topequipos[2])?></p>
                      </div>
                    </div>
                    <div class="carousel-item size-carousel">
                      <!--Mask color-->
                      <div class="view">
                        <?= Html::img("@web/images/3.png",['class'=>"d-block fotocarusel"])?>
                        <div class="mask rgba-black-slight"></div>
                      </div>
                        <div class="carousel-caption" style="padding-bottom: 420px">
                            <h3 class="h3-responsive">Top 3 mejores escaladores de montaña </h3>
                        </div>
                        <div class="carousel-caption" style="padding-bottom: 10px">
                        <p>1º. <?= implode($topescaladores[0])?></p>
                        <p>2º. <?= implode($topescaladores[1])?> </p>
                        <p>3º. <?= implode($topescaladores[2])?></p>
                      </div>
                    </div>
                  </div>
                  <!--/.Slides-->
                  <!--Controls-->
                  <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                  <!--/.Controls-->
                </div>
                <!--/.Carousel Wrapper-->
            </div>
        </div>
        <div class="col-sm-12 col-md-2 col-lg-2 card shadow-sm" style="background-color: buttonhighlight">
            <h3 style="text-align: center">Ultima hora</h3>
            <div class="row">
                <div class="col card shadow-sm">
                    <h4 class="text-justify">Gorospe cedio el liderato al italiano Giovannetti</h4>
                    <p class="text-justify">Un aspirante al mero triunfo de etapa, Carlos Hernández (Lotus), 
                       volvió a demostrar ayer que los favoritos 
                       <?= Html::a('Seguir leyendo...',['site/noticia','num'=>''])?>
                    </p>
                </div>
            </div>
             <div class="row">
                <div class="col card shadow-sm">
                    <h4 class="text-justify">Los directores de equipos asumen el riesgo de sus tácticas</h4>
                    <p class="text-justify">Los directores deportivos de los equipos españoles asumen el notable riesgo del peligroso juego táctico que han utilizado en las seis primeras etapas de la Vuelta 
                       <?= Html::a('Seguir leyendo...',['site/noticia','num'=>'2'])?>
                    </p>
                </div>
            </div>
            
        </div>
    </div>
</div>

views/site/noticia2.php
<?php
use yii\helpers\Html;
$this->title = 'Noticias';
?>


<div class="container">
    <div class="row stilobody">
        <div class="align-items-center col-10" style="padding: 30px">
            <p>VUELTA CICLISTA A ESPAÑA</p>
            <h1>Los directores de equipos asumen el riesgo de sus tácticas</h1>
            <hr>
            <p class="text-justify">Los directores deportivos de los equipos españoles asumen el notable riesgo del peligroso juego táctico que han utilizado en las seis primeras etapas de la Vuelta. El resultado es que los principales favoritos han cedido un tiempo importante respecto a corredores que, sin ser jefes de fila, pueden dar motivos a múltiples especulaciones sobre su opción para mantener sus actuales posiciones. José Miguel Echávarri (Banesto) explica su criterio sobre lo que ha sucedido hasta el momento Refiriéndose a Gorospe, Giovanetti, Cadena, Ivanov y Farfan, explica: "Hasta ahora esta mos poniendo sobre el tapete caballos y sotas y nos reservamos los ases y los reyes. Pero es un juego muy peligroso. Nadie puede estar tranquilo con esta situación, aunque nuestra posición es mejor que la de otros".Existe coincidencia unánime en definir como una "locura" el desarrollo de la carrera. No obstante, Juan Fernández (Clas) cree hasta cierto punto razonable que "todos hayamos preferido que por el momento los riesgos no los asuman nuestras mejores bazas para no machacar a nuestros equipos". Rafael Carrasco (Kelme), opina que la clasificación general "está como debe estar por la forma en la que ha ido la carrera, muy rápida y alocada. Pero estoy convencido que la lógica irá imponiéndose con el paso de los días". El máximo responsable del Kelme mantiene la teoría de que el equipo Banesto, ya antes incluso de que situara como líder a Gorospe "debía controlar porque es el más fuerte y el único que cuenta con un líder capaz de romper la carrera que es Delgado".</p>
            <p class="text-justify">Para González Linares (Teka) todos han actuado hasta el momento sin excesiva coherencia. "Si en la etapa del domingo, el Clas no llega a tirar del pelotón, los escapados hubieran sentenciado la Vuelta. Pero creo que va a ser difícil desbancar a corredores que se han situado muy bien como Ivanov, Giovanetti y Cadena". A pesar de la desventaja de los favoritos y de las especulaciones sobre la permanencia de Gorospe en el primer puesto, existe también unanimidad en cuanto a que los pronósticos iniciales siguen intactos. "No ha cambiado en absoluto la estrategia para el desenlace de la Vuelta, a pesar de que Gorospe haya roto el cerco de los grandes favoritos", aseguró Echávarri. 'To de Giovanetti y Unzaga", asegura Maximino Pérez (Seur) fue muy bonito y beneficioso para el equipo. Pero lo mejor que nos pasó el domingo fue que Pino no necesitó ser infiltrado porque está muy recuperado de su tendinitis".</p>
        </div>
        <div class="col-2 card shadow-sm" style="background-color: buttonhighlight">
            <h3 style="text-align: center">Noticias</h3>
            <div class="row">
                <div class="col card shadow-sm">
                    <h4 class="text-justify">Primer golpe de mano de Banesto en la Vuelta</h4>
                    <p class="text-justify">La omnipresencia parece ser la regla de (oro para todo aspirante a ganar la actual edición de la Vuelta a España. Desaparecer de la cabeza del pelotón, tan siquiera fugazmente, conduce directamente al furgón de cola
                       <?= Html::a('Seguir leyendo...',['site/noticia','num'=>'3'])?>
                    </p>
                </div>
            </div>
             <div class="row">
                <div class="col card shadow-sm">
                    <h4 class="text-justify">Gorospe cedio el liderato al italiano Giovannetti</h4>
                    <p class="text-justify">Un aspirante al mero triunfo de etapa, Carlos Hernández (Lotus), 
                       volvió a demostrar ayer que los favoritos 
                       <?= Html::a('Seguir leyendo...',['site/noticia','num'=>''])?>
                    </p>
                </div>
            </div>
            
        </div>
    </div>
</div>

views/site/resultado.php
<?php
use yii\grid\GridView;
?>

<div class="jumbotron">
    <h2><?=$titulo?></h2>
    
    <p class="lead"><?= $enunciado?></p>
    <div class="well">
        <?= $sql ?>
    </div>
</div>

<?=GridView::widget([
    'dataProvider'=>$resultados,
    'columns'=>$campos
]);?>